/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gestion.pack.panels;
import javax.swing.JPanel;
import gestion.pack.charts.HistogramChartBuilder;
/**
 *
 * @author ideal
 */
public class GraphPanel extends javax.swing.JPanel {
private TablePanel tablePanel;
    /**
     * Creates new form GraphPanel
     
     */
    public GraphPanel(TablePanel tablePanel) {
        this.tablePanel = tablePanel;
        initComponents();
    
        double[] stats = tablePanel.getMoyenneStats(); // min, moyenne, max
        JPanel histogram = HistogramChartBuilder.createHistogramPanel(stats);
    
        this.setLayout(new java.awt.BorderLayout());
        this.add(histogram, java.awt.BorderLayout.CENTER);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
